name: Build PolyBot

on:
  push:
    branches:
      - "*"
    tags-ignore: [ "*" ]
  pull_request:
  release:
    types: [ released ]

jobs:
  build:
    # Only run on PRs if the source branch is on someone else's repo
    if:      ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    runs-on: 'ubuntu-latest'
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Gradle Wrapper Validation"
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: "Set up JDK 17"
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          cache:        'gradle'
      - name: "Build PolyBot"
        uses: burrunan/gradle-cache-action@v1.10
        with:
          arguments:      'build shadowJar'
          gradle-version: wrapper
          concurrent:     true