name: Build PolyBot

on:
  push:
    branches:
      - "*"
    tags-ignore: [ "*" ]
  pull_request:
  release:
    types: [ released ]

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Set up JDK 17"
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          cache:        'gradle'
      - name: "Build PolyBot"
        uses: burrunan/gradle-cache-action@v1.10
        with:
          arguments:      'build shadowJar'
          gradle-version: wrapper
          concurrent:     true